import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className="min-h-screen flex flex-col">
          
          {/* Navbar placeholder */}
          <header className="border-b">
            <Navbar />
          </header>

          {/* Page content */}
          <main className="flex-1">{children}</main>

          {/* Footer placeholder */}
          <footer className="border-t">
            <p className="text-center p-3">Footer will go here</p>
          </footer>

        </div>
      </body>
    </html>
  );
}
